### ISSUE TITLE
NRF52840DK with sx1262mb2xAS shield - MCPS CONFIRM status: Rx 2 timeout

### ISSUE THREAD

**Issue by carriegong** [FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN#3]
normally getting this error for confirmed messages. at the same time it is missing downlink messages once in a while.
Where can one look to solve this issue.  
[LoRaMac] MCPS CONFIRM status: Rx 2 timeout
[LoRaWanClassA] Failed to send an uplink packet with error = 23

Unconfirmed messages are never able to get downlinks but it seems to give ok for MCPS CONFIRM status.

**Comment by ravibhagavandas** [comment]
Hi @cawahe 

MCPS CONFIRM status "ok" for unconfirmed messages just means that the packet was sent out of the radio successfully. Since it  does not wait for downlink ACK message, status does not indicate that the message is received at a gateway or a Lora Network Server. To check if the gateway has received packets you can enable logs on the gateway. Also if you are connecting to a network such as TTN you can see the logs of packets in the TTN console.

MCPS CONFIRM status: "Rx 2 timeout" indicates that the receiver window timed out to receive an acknowledgment for the packet. This could be possible if the uplink packet was not received at gateway or Lora Network Server or the downlink ACK from the Network Server was not received in device receive window duration. I would recommend starting from end node  device and try to log the data rate/frequency at which the data packet is sent and the gateway receiver is tuned to that frequency band. 

To log the current data rate used for send, you can use the following API:

```
MibRequestConfirm_t mibReq = { 0 };
mibReq.Type = MIB_CHANNELS_DATARATE;
LoRaMacMibGetRequestConfirm( &mibReq );
configPRINTF( ( "Data rate : DR_%d\n", mibReq.Param.ChannelsDatarate ) );
```
If the packet is received by the Lora Server and ACK is transmitted back to gateway then you can look for timing and data rate of Receive window on end device matches with that of server. For a list of queryable parameters you can refer the doc [here](https://stackforce.github.io/LoRaMac-doc/LoRaMac-doc-v4.4.5/group___l_o_r_a_m_a_c.html#union_mib_param__t). 

Finally you can also adjust retries for failures in sending a confirmed message uplink, by changing the config [here](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN/blob/master/demos/classA/Nordic_NRF52/config/LoRaWANConfig.h#L143). Retries will try different possible channels in the frequency band.

**Comment by cawahe** [comment]
hello @ravibhagavandas, 
Thanks for your reply! I think my problem may be that when it retries sending it send to different possible channels. How do I limit it to the channel that the program has joined to on start? and not vary the channels when sending?

**Comment by dachalco** [comment]
Hi @cawahe 

Are the RX2 timeouts intermittent or are they consistently occurring? How is the connection to the gateway, perhaps the signal is weak and packets are getting dropped? If you have access to the gateway, are you able to access the gateway's logs for further investigation?

To set channels you can use the `mibReq.Type` for the `[MIB_CHANNELS_MASK](https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c#L4622)`.

**Comment by cawahe** [comment]
RX2 timeouts are once in a while. I am right next to the gateway. It seems like when I do not get the MCPS INDICATION status: OK that is where it misses the downlink. and that's where it queues the downlink. 
Any ideas on fixing this in the code? 
I have disabled channels on join by [commenting this line out](https://github.com/Lora-net/LoRaMac-node/blob/05353ff70bec5349a26b23a02168accb0ea03ad9/src/mac/region/RegionUS915.c#L856). Is that the correct way of doing it?

**Comment by dachalco** [comment]
Hi @carriegong 

Apologies for the delay. Were you able to adjust the channels? 

As mentioned earlier, you should be able to setup the desired channels by calling 
`LoRaMacMibSetRequestConfirm( MibRequestConfirm_t* mibSet )` with request set for `MIB_CHANNELS_MASK` in [this file](https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c#L4119). I don't have a LoRa setup at the moment, so can't reproduce your issue quite yet, but should be able to once I return from holidays.

**Comment by dachalco** [comment]
Hi @carriegong 

You may also adjust `lorawanConfigRX_MAX_TIMING_ERROR` [here](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-LoRaWAN/blob/master/demos/classA/Nordic_NRF52/config/LoRaWANConfig.h#L149) to add more timing tolerance, possibly  relieving some of the RX 2 timeouts. 

As for queued downlink upon missing MCPS Indication OK, this happens because the device was unable to receive an expected message from the lora server, so that message is queued by lora server for the next available opportunity, usually in the next RW window.
